export DYNAMOS_ROOT="/home/ubuntu/scattered-directive-energy-monitoring"
export DOCKERHUB_ACCOUNT="apipilikas"
export CONFIG_PATH="${DYNAMOS_ROOT}/configuration"
export CHARTS_PATH="${DYNAMOS_ROOT}/charts"