[kube_control_plane]
control ansible_host=10.145.1.2 ip=10.145.1.2 etcd_member_name=etcd1

[etcd:children]
kube_control_plane

[kube_node]
dynamos ansible_host=10.145.1.3 ip=10.145.1.3
server ansible_host=10.145.1.4 ip=10.145.1.4
aggregator ansible_host=10.145.1.5 ip=10.145.1.5
authority ansible_host=10.145.1.6 ip=10.145.1.6
clientone ansible_host=10.145.1.7 ip=10.145.1.7
clienttwo ansible_host=10.145.1.8 ip=10.145.1.8
clientthree ansible_host=10.145.1.9 ip=10.145.1.9
surf ansible_host=10.145.1.10 ip=10.145.1.10
